Repository team-nabi/nabi-market-server, pull requests merged in 2023-11, with the labels that each got.

#7 Nabi 102 yejin refactor oauth2 google kakao
  src/main/java/org/prgrms/nabimarketbe/domain/user/Role.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/UserResponseDto.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserSignInRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/sign/UserSignupRequestDto.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/sign/UserSocialLoginRequestDto.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/sign/UserSocialSignupRequestDto.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/entity/User.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/SignService.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
  src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
  src/main/java/org/prgrms/nabimarketbe/global/security/entity/RefreshToken.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/dto/TokenDTO.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/dto/TokenRequestDto.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/provider/JwtProvider.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/repository/RefreshTokenRepository.java
  src/main/java/org/prgrms/nabimarketbe/global/util/ResponseFactory.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/google/member/dto/OAuth2Attributes.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/google/member/oauth2/service/CustomOAuth2UserService.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/kakao/api/OAuth2Controller.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/kakao/dto/KakaoProfile.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/kakao/service/CustomUserDetailsService.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/kakao/service/OAuth2Service.java
  src/main/resources/templates/social/login.ftl
  src/main/resources/templates/social/redirectKakao.ftl
  src/test/java/org/prgrms/nabimarketbe/user/controller/UserControllerTest.java
  src/test/java/org/prgrms/nabimarketbe/user/repository/UserRepositoryTest.java
  src/test/java/org/prgrms/nabimarketbe/user/service/UserServiceTest.java
Labels: Sprint-2

#15 NABI-116-feat : 카드 조회시 viewCount update
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
Labels: Sprint-2

#14 Nabi 112 yejin feat s3 upload
  build.gradle
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardCreateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardCreateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/dto/request/CardImageCreateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
  src/main/java/org/prgrms/nabimarketbe/domain/item/entity/Item.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/entity/User.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
  src/main/java/org/prgrms/nabimarketbe/global/Domain.java
  src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
  src/main/java/org/prgrms/nabimarketbe/global/config/AWSConfig.java
  src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
  src/main/resources/templates/adminPage.html
  src/test/java/org/prgrms/nabimarketbe/user/service/UserServiceTest.java
Labels: Sprint-2

#20 NABI-43--feat : 유저 조회, 유저닉네임 업데이트 구현
  .github/workflows/CICD.yml
  .github/workflows/ci.yml
  appspec.yml
  src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserGetResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserLoginResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserUpdateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/entity/User.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/CheckService.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/SignService.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
  src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/dto/TokenDTO.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/dto/TokenResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/provider/JwtProvider.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/google/dto/GoogleUserInfoDTO.java
  src/main/resources/application.yml
  src/test/java/org/prgrms/nabimarketbe/NabiMarketBeApplicationTests.java
  src/test/java/org/prgrms/nabimarketbe/oauth/controller/OAuth2ControllerTest.java
  src/test/java/org/prgrms/nabimarketbe/sign/controller/SignControllerTest.java
  src/test/java/org/prgrms/nabimarketbe/user/controller/UserControllerTest.java
  src/test/java/org/prgrms/nabimarketbe/user/repository/UserRepositoryTest.java
  src/test/java/org/prgrms/nabimarketbe/user/service/OAuth2ServiceTest.java
  src/test/java/org/prgrms/nabimarketbe/user/service/UserServiceTest.java
Labels: Sprint-3

#24 NABI-124--찜 생성, 삭제, 나의 찜 목록 조회 구현
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/api/DibController.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/dto/response/DibCreateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/dto/response/DibListReadPagingResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/dto/response/DibListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/dto/response/DibResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/entity/Dib.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/repository/DibRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/repository/DibRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/repository/DibRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/service/DibService.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/CheckService.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/SignService.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/filter/JwtAuthenticationFilter.java
Labels: Sprint-3

#27 Nabi-184--feat--complete request 생성,컨펌-history 조회
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardSummaryResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/api/CompleteRequestController.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/request/CompleteRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/CompleteRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/HistoryListReadLimitResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/HistoryListReadPagingResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/HistoryListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/entity/CompleteRequest.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/entity/CompleteRequestStatus.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepositryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/dto/response/SuggestionListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/dto/response/SuggestionResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
Labels: sprint-4

#30 NABI-124--찜 목록 조회 필드 추가
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/api/DibController.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/dto/response/DibListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/repository/DibRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/repository/DibRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/service/DibService.java
Labels: Sprint-3

#31 Nabi-189--feat : api 명세 변경으로 인한 card create, update, s3 upload
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardCreateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardCreateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardDetail.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardSingleReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardUpdateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/dto/request/CardImageCreateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/dto/response/CardImageCreateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/dto/response/CardImageSingleReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/dto/response/CardImageUpdateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/repository/CardImageRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
  src/main/java/org/prgrms/nabimarketbe/domain/item/entity/Item.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserSummaryResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
  src/main/java/org/prgrms/nabimarketbe/global/aws/api/S3FileController.java
  src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
  src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
Labels: sprint-4

#33 NABI-205--refactor : suggestionInfo, cardInfo 명시
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/dto/response/SuggestionDetailResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/dto/response/SuggestionListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/repository/SuggestionRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
Labels: sprint-4

#35 Nabi-206--refactor api 제안가능한 카드들 (no.8)
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardDetail.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardInfo.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/SuggestionAvailableCardResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/SuggestionInfo.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
Labels: sprint-4

#34 NABI-204 기존 api 예외케이스에 따른 코드 수정
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardCreateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardCreateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardDetail.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardUpdateResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
  src/main/java/org/prgrms/nabimarketbe/domain/category/entity/Category.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/api/CompleteRequestController.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/repository/DibRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/Suggestion.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/SuggestionType.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/repository/SuggestionRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: sprint-4

#37 Nabi-230--refactor : JDBC Batch Insert
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardDetail.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/repository/CardImageBatchRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/service/CardImageService.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/HistoryListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
Labels: sprint-4

#41 NABI-230--refactor : api-s3 이미지 업로드 url path
  src/main/java/org/prgrms/nabimarketbe/global/aws/api/S3FileController.java
  src/main/java/org/prgrms/nabimarketbe/global/aws/service/S3FileUploadService.java
Labels: sprint-4

#42 Nabi-230--refactor : Refresh Token 로그인시 save 되는 이슈 해결
  src/main/java/org/prgrms/nabimarketbe/global/security/entity/RefreshToken.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/provider/JwtProvider.java
Labels: sprint-4

#43 NABI-253-- beommo hotfix category
  src/main/java/org/prgrms/nabimarketbe/domain/category/entity/Category.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/provider/JwtProvider.java
  src/main/resources/data.sql
Labels: sprint-4

#44 NABI-254--delete : 기존 테스트 삭제
  .github/workflows/CICD.yml
  scripts/deploy.sh
  src/test/java/org/prgrms/nabimarketbe/NabiMarketBeApplicationTest.java
  src/test/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryTest.java
Labels: sprint-4

#45 NABI-257--fix : batch insert, field명 수정
  .github/workflows/CICD.yml
  build.gradle
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardStatusUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardDetailResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/repository/CardImageBatchRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserSummaryResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserUpdateResponseDTO.java
Labels: sprint-4

#46 Nabi-252--fix suggestion available cards 조회 이슈 해결. poke validation 조건 추가
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/SuggestionType.java
Labels: sprint-4

#48 NABI-250--feat : 인기상품 조회 기능 추가
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/projection/CardFamousResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/global/error/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: sprint-4

#49 NO-JIRA--hotfix : 유저 프로필 업데이트 body로 받도록 변경
  src/main/java/org/prgrms/nabimarketbe/domain/user/api/UserController.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserNicknameUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserProfileUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
Labels: Sprint-5

#50 Nabi-NO-JIRA-fix : 이미지 다중 업로드 에러 로직 제거
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/repository/CardImageBatchRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/wrapper/HistoryListReadPagingResponseDTO.java
Labels: Sprint-5

#52 NO-JIRA--refactor : 프론트 요청에 따라 images에 thumbnail append 삭제
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
Labels: Sprint-5

#53 Nabi-261--fix : 썸네일에 null 이 들어가는 이슈 해결
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/projection/CardInfoResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
Labels: Sprint-5

#54 NABI-NO-JIRA : suggestion update request param -> body
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/api/SuggestionController.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/dto/request/SuggestionUpdateRequestDTO.java
Labels: bug

#55 NABI-199--feat : 알림 기능 구현
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/entity/CompleteRequest.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/api/NotificationController.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/request/NotificationReadRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/response/NotificationUnreadCountResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/response/projection/NotificationDetailResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/response/wrapper/NotificationListResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/response/wrapper/NotificationPagingResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/response/wrapper/NotificationResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/entity/Notification.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/repository/NotificationRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/repository/NotificationRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/repository/NotificationRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/service/NotificationService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/Suggestion.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/SuggestionType.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/repository/SuggestionRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/repository/SuggestionRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
  src/main/java/org/prgrms/nabimarketbe/global/event/NotificationCreateEvent.java
  src/main/java/org/prgrms/nabimarketbe/global/event/NotificationEventHandler.java
  src/main/java/org/prgrms/nabimarketbe/global/util/QueryDslUtil.java
Labels: Sprint-5

#57 Nabi-288-feat : complete request get api
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/CardCondenseResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/response/wrapper/CardUserSummaryResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/api/CompleteRequestController.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/wrapper/CompleteRequestInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/response/wrapper/CompleteRequestSummaryDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/response/UserIdResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
Labels: Sprint-5

#58 NABI-290 : 채팅방 정보 단건 조회
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/api/CharRoomController.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/CardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/ChatRoomInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/ChatRoomInfoWrapper.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/FromCardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/ToCardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/UserInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/entity/ChatRoom.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/repository/ChatRoomRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/repository/ChatRoomRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/service/ChatRoomService.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepository.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
Labels: Sprint-5

#59 NABI-287--chore : 로그백 설정
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.properties
Labels: Sprint-5

#60 NO-JIRA--hotfix : api명세에 맞게 코드 수정
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/dto/response/projection/DibListReadResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/repository/DibRepositoryImpl.java
Labels: Sprint-5

#62 NABI-304 : 채팅방 목록 조회
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/api/CharRoomController.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/CardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/ChatRoomInfoWrapper.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/FromCardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/ToCardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/UserInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/list/CardInfoListDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/list/ChatRoomInfoListDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/list/ChatRoomListWrapper.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/list/FromCardInfoListDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/list/ToCardInfoListDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/list/UserInfoListDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/single/CardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/single/ChatRoomInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/single/ChatRoomInfoWrapper.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/single/FromCardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/single/ToCardInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/dto/response/single/UserInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/repository/ChatRoomRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/service/ChatRoomService.java
Labels: Sprint-5

#61 NABI-298--test : 유저서비스 테스트 작성
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/response/wrapper/NotificationListResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/notifiaction/dto/response/wrapper/NotificationResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/SocialUserInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserSignInRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/SignService.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/google/api/GoogleOAuth2Controller.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/google/service/GoogleOAuth2Service.java
  src/main/java/org/prgrms/nabimarketbe/oauth2/kakao/api/OAuth2Controller.java
  src/test/java/org/prgrms/nabimarketbe/domain/user/service/SignServiceTest.java
  src/test/java/org/prgrms/nabimarketbe/domain/user/service/UserServiceTest.java
  src/test/java/org/prgrms/nabimarketbe/setup/jwt/TokenResponseDTOBuilder.java
  src/test/java/org/prgrms/nabimarketbe/setup/oauth2/request/SocialUserInfoDTOBuilder.java
  src/test/java/org/prgrms/nabimarketbe/setup/user/UserBuilder.java
  src/test/java/org/prgrms/nabimarketbe/setup/user/request/UserNicknameUpdateRequestDTOBuilder.java
  src/test/java/org/prgrms/nabimarketbe/setup/user/request/UserProfileUpdateRequestDTOBuilder.java
Labels: Sprint-5

#64 NO-JIRA--hotfix : dto, entity contraint 추가
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardCreateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/dto/request/CardUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
  src/main/java/org/prgrms/nabimarketbe/domain/cardimage/dto/request/CardImageCreateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/request/CompleteRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/dto/request/SuggestionRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/dto/request/SuggestionUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/SocialUserInfoDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserNicknameUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserProfileUpdateRequestDTO.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/dto/request/UserRequestDTO.java
Labels: Sprint-5

#65 NABI-307: Card Delete
  src/main/java/org/prgrms/nabimarketbe/domain/card/api/CardController.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/entity/Card.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepositoryImpl.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/repository/SuggestionRepositoryImpl.java
Labels: Sprint-5

#66 Nabi-306--fix : 제안가능 카드 목록 조회 (이미 제안 내역이 있는 카드 제외)
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/chatroom/service/ChatRoomService.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/entity/CompleteRequest.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/Suggestion.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/repository/SuggestionRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
Labels: Sprint-5

#70 NO-JIRA--hotfix : 거래성사요청 수락/거절 dto
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/api/CompleteRequestController.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/dto/request/CompleteRequestUpdateDTO.java
Labels: bug

#67 NO-JIRA--feat : 닉네임 중복 check, @Retryable 어노테이션 추가
  build.gradle
  src/main/java/org/prgrms/nabimarketbe/NabiMarketBeApplication.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/entity/User.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/RandomNicknameGenerator.java
  src/main/java/org/prgrms/nabimarketbe/domain/user/service/UserService.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
  src/main/resources/logback-variables.properties
  src/test/java/org/prgrms/nabimarketbe/domain/user/service/RandomNicknameGeneratorTest.java
Labels: Sprint-5

#72 NO-JIRA--fix : 알림 대상 카드 수정
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/entity/Suggestion.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
Labels: Sprint-5

#74 NO-JIRA--hotfix : 거래성사 요청 시 이미 요청에 존재하는 fromCard, toCard block
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
Labels: bug

#75 NO-JIRA--hotfix : 제안 확인 조건 추가
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/repository/SuggestionRepositoryImpl.java
Labels: Sprint-6

#77 NO-JIRA--hotfix : 거래 제안 시 카드 validate, 제안 가능한 카드 목록 AVAILVABLE만 내려주기
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
Labels: bug

#81 NO-JIRA--hotfix : suggestion complete request bug
  src/main/java/org/prgrms/nabimarketbe/domain/card/repository/CardRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/card/service/CardService.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/entity/CompleteRequest.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/entity/CompleteRequestStatus.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/repository/CompleteRequestRepository.java
  src/main/java/org/prgrms/nabimarketbe/domain/completeRequest/service/CompleteRequestService.java
  src/main/java/org/prgrms/nabimarketbe/domain/dibs/service/DibService.java
  src/main/java/org/prgrms/nabimarketbe/domain/suggestion/service/SuggestionService.java
Labels: bug, Sprint-6

#79 NO-JIRA---jwt토큰 반환값 hotfix
  src/main/java/org/prgrms/nabimarketbe/global/config/SecurityConfiguration.java
  src/main/java/org/prgrms/nabimarketbe/global/error/ErrorCode.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/dto/TokenErrorResponseDTO.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/filter/JwtExceptionFilter.java
  src/main/java/org/prgrms/nabimarketbe/global/security/jwt/provider/JwtProvider.java
Labels: Sprint-6
